services:
  plantuml-c4model:
    container_name: plantuml-c4model
    image: plantuml/plantuml-server
    ports:
      - "8080:8080"
    networks:
      - microservices-net
  microservice-wallet-core:
    container_name: microservice-wallet-core
    build: 
      # context: .
      dockerfile: ./wallet-core/Dockerfile.dev
    volumes:
      - ./:/workspace
    working_dir: /workspace/wallet-core
    networks:
      - microservices-net
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      
  utils-package:
    container_name: utils-package
    build:
      dockerfile: ./utils-package/Dockerfile.dev
    volumes:
      - ./:/workspace
    working_dir: /workspace/utils-package
    networks:
      - microservices-net
  

networks:
  microservices-net:
    driver: bridge